In [33]:
import tensorflow as tf

In [34]:
import keras

In [35]:
dir(keras)

['Input',
 'Model',
 'Sequential',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'absolute_import',
 'activations',
 'applications',
 'backend',
 'callbacks',
 'constraints',
 'datasets',
 'engine',
 'initializers',
 'layers',
 'legacy',
 'losses',
 'metrics',
 'models',
 'optimizers',
 'preprocessing',
 'regularizers',
 'utils',
 'wrappers']

### karas基础模块

In [36]:
from keras.models import Sequential

In [37]:
model=Sequential()

In [38]:
from keras.layers import Dense

In [39]:
model.add(layer=Dense(64,activation='relu'))

In [40]:
model.add(layer=Dense(64,activation='relu'))

In [41]:
model.add(layer=Dense(32,activation='softmax'))

### 构建好模型之后，通过调用compile方法配置该模型的学习流程

In [42]:
model.compile(optimizer=keras.optimizers.Adam(0.001),
            loss=keras.losses.categorical_crossentropy,
             metrics=[keras.metrics.categorical_accuracy]) 

  optimizer：优化器，如Adam
  loss：计算损失，这里用的是交叉熵损失
  metrics: 列表，包含评估模型在训练和测试时的性能的指标，典型用法是metrics=[‘accuracy’]。如果要在多输出模型中为不同的输出指定不同的指标，可向该参数传递一个字典，例如metrics={‘output_a’: ‘accuracy’}


### 输入numpy数据

In [43]:
import numpy as np

In [47]:

train_x = np.random.random((1000,72)) #上面这个就代表生成1000行 72列的浮点数，浮点数都是从0-1中随机。
train_y = np.random.random((1000,10))
val_x = np.random.random((200,72))
val_y = np.random.random((200,10))
model.fit(train_x, train_y, epochs=10, batch_size=32,
          validation_data=(val_x, val_y))



ValueError: Error when checking target: expected dense_6 to have shape (32,) but got array with shape (10,)

In [45]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))

In [46]:
print(train_x,'\n',train_y,'\n',dataset)

[[0.82309089 0.18429109 0.67260834 ... 0.52727324 0.32023213 0.60815703]
 [0.87389544 0.31842404 0.99558932 ... 0.71142722 0.5905179  0.38287561]
 [0.51606252 0.62685001 0.8801696  ... 0.54097044 0.34981397 0.46789267]
 ...
 [0.98029676 0.04132222 0.01365066 ... 0.30109009 0.92748172 0.52611415]
 [0.91202371 0.31658473 0.65380848 ... 0.9628189  0.33630205 0.2644686 ]
 [0.13808771 0.6469669  0.87184309 ... 0.79499416 0.43320548 0.73630449]] 
 [[0.54110582 0.2931069  0.79751261 ... 0.69963547 0.30276386 0.87484252]
 [0.64029975 0.38768508 0.56574429 ... 0.87457651 0.32057074 0.4433723 ]
 [0.25875921 0.47686649 0.68803313 ... 0.46839266 0.14734332 0.01705431]
 ...
 [0.29189829 0.3668065  0.85677246 ... 0.37908887 0.92298544 0.05165734]
 [0.76299815 0.25882231 0.67257664 ... 0.56873096 0.31456053 0.3307589 ]
 [0.49444832 0.24562153 0.98061838 ... 0.25976752 0.52746251 0.43161862]] 
 <TensorSliceDataset shapes: ((72,), (10,)), types: (tf.float64, tf.float64)>
